name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write  # Grant write access to contents
  pull-requests: write  # Grant write access to PRs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      # other steps...
